#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyVote.UI.Resource", IsApplication=true)]

namespace MyVote.UI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MyVote.BusinessObjects.Resource.String.ApplicationName = global::MyVote.UI.Resource.String.ApplicationName;
			global::MyVote.BusinessObjects.Resource.String.Hello = global::MyVote.UI.Resource.String.Hello;
			global::MyVote.Core.Resource.String.ApplicationName = global::MyVote.UI.Resource.String.ApplicationName;
			global::MyVote.Core.Resource.String.Hello = global::MyVote.UI.Resource.String.Hello;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_active_month_bg = global::MyVote.UI.Resource.Color.calendar_active_month_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_bg = global::MyVote.UI.Resource.Color.calendar_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_divider = global::MyVote.UI.Resource.Color.calendar_divider;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_highlighted_day_bg = global::MyVote.UI.Resource.Color.calendar_highlighted_day_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_inactive_month_bg = global::MyVote.UI.Resource.Color.calendar_inactive_month_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_selected_day_bg = global::MyVote.UI.Resource.Color.calendar_selected_day_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_selected_range_bg = global::MyVote.UI.Resource.Color.calendar_selected_range_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_active = global::MyVote.UI.Resource.Color.calendar_text_active;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_inactive = global::MyVote.UI.Resource.Color.calendar_text_inactive;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_selected = global::MyVote.UI.Resource.Color.calendar_text_selected;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_selector = global::MyVote.UI.Resource.Color.calendar_text_selector;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_unselectable = global::MyVote.UI.Resource.Color.calendar_text_unselectable;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_day_headers_paddingbottom = global::MyVote.UI.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_month_title_bottommargin = global::MyVote.UI.Resource.Dimension.calendar_month_title_bottommargin;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_month_topmargin = global::MyVote.UI.Resource.Dimension.calendar_month_topmargin;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_text_medium = global::MyVote.UI.Resource.Dimension.calendar_text_medium;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_text_small = global::MyVote.UI.Resource.Dimension.calendar_text_small;
			global::Xamarin.Forms.Labs.Droid.Resource.Drawable.ad16 = global::MyVote.UI.Resource.Drawable.ad16;
			global::Xamarin.Forms.Labs.Droid.Resource.Drawable.calendar_bg_selector = global::MyVote.UI.Resource.Drawable.calendar_bg_selector;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.calendar_grid = global::MyVote.UI.Resource.Id.calendar_grid;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.calendar_view = global::MyVote.UI.Resource.Id.calendar_view;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.title = global::MyVote.UI.Resource.Id.title;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.calendar_picker = global::MyVote.UI.Resource.Layout.calendar_picker;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.dialog = global::MyVote.UI.Resource.Layout.dialog;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.month = global::MyVote.UI.Resource.Layout.month;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.week = global::MyVote.UI.Resource.Layout.week;
			global::Xamarin.Forms.Labs.Droid.Resource.String.day_name_format = global::MyVote.UI.Resource.String.day_name_format;
			global::Xamarin.Forms.Labs.Droid.Resource.String.full_date_format = global::MyVote.UI.Resource.String.full_date_format;
			global::Xamarin.Forms.Labs.Droid.Resource.String.invalid_date = global::MyVote.UI.Resource.String.invalid_date;
			global::Xamarin.Forms.Labs.Droid.Resource.String.library_name = global::MyVote.UI.Resource.String.library_name;
			global::Xamarin.Forms.Labs.Droid.Resource.String.month_name_format = global::MyVote.UI.Resource.String.month_name_format;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell = global::MyVote.UI.Resource.Style.CalendarCell;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell_CalendarDate = global::MyVote.UI.Resource.Style.CalendarCell_CalendarDate;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell_DayHeader = global::MyVote.UI.Resource.Style.CalendarCell_DayHeader;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarTitle = global::MyVote.UI.Resource.Style.CalendarTitle;
			global::Xamarin.InsightsCore.Resource.String.ApplicationName = global::MyVote.UI.Resource.String.ApplicationName;
			global::Xamarin.InsightsCore.Resource.String.Hello = global::MyVote.UI.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090001
			public const int poll_categories = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int poll_views = 2131296256;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000d
			public const int black = 2131034125;
			
			// aapt resource value: 0x7f050013
			public const int blue = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int calendar_active_month_bg = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int calendar_bg = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int calendar_divider = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int calendar_highlighted_day_bg = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int calendar_inactive_month_bg = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_selected_day_bg = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int calendar_selected_range_bg = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int calendar_text_active = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int calendar_text_inactive = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int calendar_text_selected = 2131034121;
			
			// aapt resource value: 0x7f050014
			public const int calendar_text_selector = 2131034132;
			
			// aapt resource value: 0x7f05000a
			public const int calendar_text_unselectable = 2131034122;
			
			// aapt resource value: 0x7f05000f
			public const int grey = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int lightgrey = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int listseparator = 2131034129;
			
			// aapt resource value: 0x7f05000b
			public const int solid_red = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int transparent = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int white = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int yellow = 2131034130;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar_day_headers_paddingbottom = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int calendar_month_title_bottommargin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int calendar_month_topmargin = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int calendar_text_medium = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_text_small = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendar_bg_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_facebook = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_google = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_microsoft = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_twitter = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int login_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int NoImage = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int MvxBindingTagUnique = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int calendar_grid = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int calendar_view = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int title = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_picker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int month = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SplashScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int week = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int day_name_format = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int full_date_format = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int global_female_string = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int global_male_string = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int global_welcome_string = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int invalid_date = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int month_name_format = 2130968581;
			
			// aapt resource value: 0x7f04000f
			public const int polls_count_string = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int polls_title_string = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int registration_dob_string = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int registration_email_string = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int registration_username_string = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int registration_zip_string = 2130968589;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int Theme_Splash = 2131165188;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
