#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyVote.UI.Droid.Resource", IsApplication=false)]

namespace MyVote.UI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int slide_out_right = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070001
			public static int poll_categories = 2131165185;
			
			// aapt resource value: 0x7f070000
			public static int poll_views = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public static int black = 2131099650;
			
			// aapt resource value: 0x7f060008
			public static int blue = 2131099656;
			
			// aapt resource value: 0x7f060004
			public static int grey = 2131099652;
			
			// aapt resource value: 0x7f060003
			public static int lightgrey = 2131099651;
			
			// aapt resource value: 0x7f060006
			public static int listseparator = 2131099654;
			
			// aapt resource value: 0x7f060009
			public static int social_login_button = 2131099657;
			
			// aapt resource value: 0x7f060000
			public static int solid_red = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int transparent = 2131099649;
			
			// aapt resource value: 0x7f060005
			public static int white = 2131099653;
			
			// aapt resource value: 0x7f060007
			public static int yellow = 2131099655;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int android_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int custom_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int defaultlandscape = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int defaultportrait = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int facebook = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int google = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int image_not_available = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int landscapepagebackgrounddark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int logo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int logo_tiny = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int microsoft = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int photo_not_available = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int twitter = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001c
			public static int FacebookButton = 2131296284;
			
			// aapt resource value: 0x7f09001e
			public static int GoogleButton = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public static int MicrosoftButton = 2131296285;
			
			// aapt resource value: 0x7f090028
			public static int PollSearchResultImage = 2131296296;
			
			// aapt resource value: 0x7f09003b
			public static int SubmitRegistrationButton = 2131296315;
			
			// aapt resource value: 0x7f090029
			public static int Text1 = 2131296297;
			
			// aapt resource value: 0x7f09002a
			public static int Text2 = 2131296298;
			
			// aapt resource value: 0x7f09001b
			public static int TwitterButton = 2131296283;
			
			// aapt resource value: 0x7f090026
			public static int addPollButton = 2131296294;
			
			// aapt resource value: 0x7f090012
			public static int addPollEndDateButton = 2131296274;
			
			// aapt resource value: 0x7f090010
			public static int addPollStartDateButton = 2131296272;
			
			// aapt resource value: 0x7f090011
			public static int addpoll_endDateLabel = 2131296273;
			
			// aapt resource value: 0x7f09000f
			public static int addpoll_startDateLabel = 2131296271;
			
			// aapt resource value: 0x7f09003e
			public static int android_button = 2131296318;
			
			// aapt resource value: 0x7f090006
			public static int answerA = 2131296262;
			
			// aapt resource value: 0x7f090007
			public static int answerB = 2131296263;
			
			// aapt resource value: 0x7f090008
			public static int answerC = 2131296264;
			
			// aapt resource value: 0x7f090009
			public static int answerD = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public static int answerE = 2131296266;
			
			// aapt resource value: 0x7f09001f
			public static int barChart = 2131296287;
			
			// aapt resource value: 0x7f090005
			public static int categorySpinner = 2131296261;
			
			// aapt resource value: 0x7f090020
			public static int closeVoteButtonn = 2131296288;
			
			// aapt resource value: 0x7f09003f
			public static int custom_button = 2131296319;
			
			// aapt resource value: 0x7f090021
			public static int deletePollButtonn = 2131296289;
			
			// aapt resource value: 0x7f090004
			public static int description = 2131296260;
			
			// aapt resource value: 0x7f090015
			public static int editText1 = 2131296277;
			
			// aapt resource value: 0x7f090016
			public static int editText2 = 2131296278;
			
			// aapt resource value: 0x7f090017
			public static int editText3 = 2131296279;
			
			// aapt resource value: 0x7f090018
			public static int editText4 = 2131296280;
			
			// aapt resource value: 0x7f090019
			public static int editText5 = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public static int editText6 = 2131296282;
			
			// aapt resource value: 0x7f09000c
			public static int endDateTimeRadioOptions = 2131296268;
			
			// aapt resource value: 0x7f090014
			public static int fragmentContainer = 2131296276;
			
			// aapt resource value: 0x7f090025
			public static int goToNewLayoutButton = 2131296293;
			
			// aapt resource value: 0x7f090001
			public static int linearLayout1 = 2131296257;
			
			// aapt resource value: 0x7f090002
			public static int linearLayout2 = 2131296258;
			
			// aapt resource value: 0x7f09000b
			public static int newPollImage = 2131296267;
			
			// aapt resource value: 0x7f090003
			public static int pollDescription = 2131296259;
			
			// aapt resource value: 0x7f090024
			public static int pollListView2 = 2131296292;
			
			// aapt resource value: 0x7f090022
			public static int pollTypeSpinner = 2131296290;
			
			// aapt resource value: 0x7f090023
			public static int pollsPageSearchField = 2131296291;
			
			// aapt resource value: 0x7f090033
			public static int polls_layout = 2131296307;
			
			// aapt resource value: 0x7f09002b
			public static int pollview_catagoryCount = 2131296299;
			
			// aapt resource value: 0x7f090032
			public static int pollview_catagoryLinearLayout = 2131296306;
			
			// aapt resource value: 0x7f09002c
			public static int pollview_catagoryTitle = 2131296300;
			
			// aapt resource value: 0x7f09002d
			public static int pollview_cellImage = 2131296301;
			
			// aapt resource value: 0x7f09002e
			public static int pollview_cellTitle = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public static int pollview_logoImage = 2131296303;
			
			// aapt resource value: 0x7f090030
			public static int pollview_voteCounts = 2131296304;
			
			// aapt resource value: 0x7f090013
			public static int postPollButton = 2131296275;
			
			// aapt resource value: 0x7f09000d
			public static int radioButton1 = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public static int radioButton2 = 2131296270;
			
			// aapt resource value: 0x7f090039
			public static int radioFemale = 2131296313;
			
			// aapt resource value: 0x7f090038
			public static int radioMale = 2131296312;
			
			// aapt resource value: 0x7f090036
			public static int registration_dob = 2131296310;
			
			// aapt resource value: 0x7f090034
			public static int registration_email = 2131296308;
			
			// aapt resource value: 0x7f090037
			public static int registration_sex = 2131296311;
			
			// aapt resource value: 0x7f090035
			public static int registration_username = 2131296309;
			
			// aapt resource value: 0x7f09003a
			public static int registration_zip = 2131296314;
			
			// aapt resource value: 0x7f090000
			public static int scrollView1 = 2131296256;
			
			// aapt resource value: 0x7f090027
			public static int searchButton = 2131296295;
			
			// aapt resource value: 0x7f090031
			public static int searchLayout = 2131296305;
			
			// aapt resource value: 0x7f09003d
			public static int submitVoteButtonn = 2131296317;
			
			// aapt resource value: 0x7f09003c
			public static int viewPollResponses = 2131296316;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int addpoll = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int answerpoll_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int edituser = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int pollresults = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int polls = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int pollsearchresultcell = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int pollview_catagorytitle = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int pollview_container = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int pollview_new = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int registration = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public static int viewpoll = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public static int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public static int global_female_string = 2131034115;
			
			// aapt resource value: 0x7f050002
			public static int global_male_string = 2131034114;
			
			// aapt resource value: 0x7f050004
			public static int global_welcome_string = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public static int polls_count_string = 2131034122;
			
			// aapt resource value: 0x7f050009
			public static int polls_title_string = 2131034121;
			
			// aapt resource value: 0x7f050007
			public static int registration_dob_string = 2131034119;
			
			// aapt resource value: 0x7f050005
			public static int registration_email_string = 2131034117;
			
			// aapt resource value: 0x7f050006
			public static int registration_username_string = 2131034118;
			
			// aapt resource value: 0x7f050008
			public static int registration_zip_string = 2131034120;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public static int addpoll_edittext = 2131230722;
			
			// aapt resource value: 0x7f080004
			public static int addpoll_text = 2131230724;
			
			// aapt resource value: 0x7f080000
			public static int login_button = 2131230720;
			
			// aapt resource value: 0x7f080001
			public static int registration_edittext = 2131230721;
			
			// aapt resource value: 0x7f080003
			public static int registration_text = 2131230723;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
