/*
Deployment script for myvote_data_db

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "myvote_data_db"
:setvar DefaultFilePrefix "myvote_data_db"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
PRINT N'Rename refactoring operation with key 877b38f6-b7e4-401e-9124-0f8181c4c905 is skipped, element [dbo].[MVGeography].[zip] (SqlSimpleColumn) will not be renamed to Zip';


GO
PRINT N'Rename refactoring operation with key 7ff93bd3-615a-4de2-a463-efb03f9e330c is skipped, element [dbo].[MVGeography].[primary_city] (SqlSimpleColumn) will not be renamed to Primary_City';


GO
PRINT N'Rename refactoring operation with key ebde2917-f2b4-4c9f-b381-c92c7e10e79b is skipped, element [dbo].[MVGeography].[state] (SqlSimpleColumn) will not be renamed to State';


GO
PRINT N'Rename refactoring operation with key e0404f80-1491-4042-b36d-2e9f4e5b19a0 is skipped, element [dbo].[MVGeography].[county] (SqlSimpleColumn) will not be renamed to County';


GO
PRINT N'Rename refactoring operation with key 1f620df8-309a-417b-b911-503b029bd6e9 is skipped, element [dbo].[MVGeography].[timezone] (SqlSimpleColumn) will not be renamed to TimeZone';


GO
PRINT N'Rename refactoring operation with key 7415136f-3184-460e-a9cd-dd07f1a93fa3 is skipped, element [dbo].[MVGeography].[area_codes] (SqlSimpleColumn) will not be renamed to Area_Codes';


GO
PRINT N'Rename refactoring operation with key 8026583d-4352-468a-b210-4152d0df41c0 is skipped, element [dbo].[MVGeography].[latitude] (SqlSimpleColumn) will not be renamed to Latitude';


GO
PRINT N'Rename refactoring operation with key 0530222a-6be8-4364-8b84-97e5c7d7db61 is skipped, element [dbo].[MVGeography].[longitude] (SqlSimpleColumn) will not be renamed to Longitude';


GO
PRINT N'Rename refactoring operation with key f254d4b7-872d-424a-9ac6-ec9af5d0de92 is skipped, element [dbo].[MVGeography].[estimated_population] (SqlSimpleColumn) will not be renamed to Estimated_Population';


GO
PRINT N'Creating [MyVote]...';


GO
CREATE SCHEMA [MyVote]
    AUTHORIZATION [dbo];


GO
PRINT N'Creating [Reports]...';


GO
CREATE SCHEMA [Reports]
    AUTHORIZATION [dbo];


GO
PRINT N'Creating [MyVote].[MyVotePhotos]...';


GO
CREATE TABLE [MyVote].[MyVotePhotos] (
    [id] BIGINT IDENTITY (1, 1) NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating [MyVote].[ActiveUsers]...';


GO
CREATE TABLE [MyVote].[ActiveUsers] (
    [id]            BIGINT         IDENTITY (1, 1) NOT NULL,
    [AuthnToken]    NVARCHAR (MAX) NULL,
    [containerName] NVARCHAR (MAX) NULL,
    [resourceName]  NVARCHAR (MAX) NULL,
    [sas]           NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating [dbo].[MVCategory]...';


GO
CREATE TABLE [dbo].[MVCategory] (
    [CategoryID]   INT           NOT NULL,
    [CategoryName] NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([CategoryID] ASC)
);


GO
PRINT N'Creating [dbo].[MVDates]...';


GO
CREATE TABLE [dbo].[MVDates] (
    [DateKey]              INT          NOT NULL,
    [DateID]               DATE         NOT NULL,
    [DayNme]               VARCHAR (50) NOT NULL,
    [DayShort]             CHAR (10)    NOT NULL,
    [DayNOD]               TINYINT      NOT NULL,
    [CalendarYear]         SMALLINT     NOT NULL,
    [CalendarYearNOD]      SMALLINT     NOT NULL,
    [CalendarQuarter]      INT          NOT NULL,
    [CalendarQuarterName]  CHAR (15)    NOT NULL,
    [CalendarQuarterShort] CHAR (7)     NOT NULL,
    [CalendarQuarterNOD]   TINYINT      NOT NULL,
    [CalendarMonth]        INT          NOT NULL,
    [CalendarMonthName]    VARCHAR (20) NOT NULL,
    [CalendarMonthShort]   CHAR (8)     NOT NULL,
    [CalendarMonthNOD]     TINYINT      NOT NULL,
    [CalendarWeek]         INT          NOT NULL,
    [CalendarWeekName]     VARCHAR (20) NOT NULL,
    [CalendarWeekShort]    CHAR (9)     NOT NULL,
    [CalendarWeekNOD]      TINYINT      NOT NULL,
    CONSTRAINT [pk_MVDates] PRIMARY KEY CLUSTERED ([DateKey] ASC)
);


GO
PRINT N'Creating [dbo].[MVGeography]...';


GO
CREATE TABLE [dbo].[MVGeography] (
    [GeographyKey]         INT          IDENTITY (1, 1) NOT NULL,
    [Zip]                  VARCHAR (50) NULL,
    [Primary_City]         VARCHAR (50) NULL,
    [State]                VARCHAR (50) NULL,
    [County]               VARCHAR (50) NULL,
    [TimeZone]             VARCHAR (50) NULL,
    [Area_Codes]           VARCHAR (50) NULL,
    [Latitude]             VARCHAR (50) NULL,
    [Longitude]            VARCHAR (50) NULL,
    [Estimated_Population] VARCHAR (50) NULL,
    CONSTRAINT [pk_MVGeography] PRIMARY KEY CLUSTERED ([GeographyKey] ASC)
);


GO
PRINT N'Creating [dbo].[MVPoll]...';


GO
CREATE TABLE [dbo].[MVPoll] (
    [PollID]               INT             IDENTITY (1, 1) NOT NULL,
    [UserID]               INT             NOT NULL,
    [PollCategoryID]       INT             NOT NULL,
    [PollQuestion]         NVARCHAR (1000) NOT NULL,
    [PollDescription]      NVARCHAR (MAX)  NULL,
    [PollImageLink]        NVARCHAR (500)  NULL,
    [PollMaxAnswers]       SMALLINT        NULL,
    [PollMinAnswers]       SMALLINT        NULL,
    [PollStartDate]        DATETIME2 (7)   NOT NULL,
    [PollEndDate]          DATETIME2 (7)   NOT NULL,
    [PollAdminRemovedFlag] BIT             NULL,
    [PollDateRemoved]      DATETIME2 (7)   NULL,
    [PollDeletedFlag]      BIT             NULL,
    [PollDeletedDate]      DATETIME2 (7)   NULL,
    [AuditDateCreated]     DATETIME2 (7)   NULL,
    [AuditDateModified]    DATETIME2 (7)   NULL,
    CONSTRAINT [pk_MVPoll] PRIMARY KEY CLUSTERED ([PollID] ASC)
);


GO
PRINT N'Creating [dbo].[MVPollComment]...';


GO
CREATE TABLE [dbo].[MVPollComment] (
    [PollCommentID]          INT             IDENTITY (1, 1) NOT NULL,
    [UserID]                 INT             NOT NULL,
    [CommentText]            NVARCHAR (1000) NULL,
    [CommentDate]            DATETIME2 (7)   NULL,
    [ParentCommentID]        INT             NULL,
    [PollID]                 INT             NOT NULL,
    [PollCommentDeletedFlag] BIT             NULL,
    [PollCommentDeletedDate] DATETIME2 (7)   NULL,
    CONSTRAINT [pk_MVPollComment] PRIMARY KEY CLUSTERED ([PollCommentID] ASC)
);


GO
PRINT N'Creating [dbo].[MVPollOption]...';


GO
CREATE TABLE [dbo].[MVPollOption] (
    [PollOptionID]   INT            IDENTITY (1, 1) NOT NULL,
    [PollID]         INT            NOT NULL,
    [OptionPosition] SMALLINT       NOT NULL,
    [OptionText]     NVARCHAR (200) NOT NULL,
    CONSTRAINT [pk_MVPollOption] PRIMARY KEY CLUSTERED ([PollOptionID] ASC)
);


GO
PRINT N'Creating [dbo].[MVPollResponse]...';


GO
CREATE TABLE [dbo].[MVPollResponse] (
    [PollResponseID]   INT           IDENTITY (1, 1) NOT NULL,
    [PollID]           INT           NOT NULL,
    [PollSubmissionID] INT           NOT NULL,
    [UserID]           INT           NOT NULL,
    [PollOptionID]     INT           NOT NULL,
    [OptionSelected]   BIT           NOT NULL,
    [ResponseDate]     DATETIME2 (7) NOT NULL,
    CONSTRAINT [pk_MVPollResponse] PRIMARY KEY CLUSTERED ([PollResponseID] ASC)
);


GO
PRINT N'Creating [dbo].[MVPollSubmission]...';


GO
CREATE TABLE [dbo].[MVPollSubmission] (
    [PollSubmissionID]      INT             IDENTITY (1, 1) NOT NULL,
    [PollID]                INT             NOT NULL,
    [UserID]                INT             NOT NULL,
    [PollSubmissionDate]    DATETIME2 (7)   NOT NULL,
    [PollSubmissionComment] NVARCHAR (1000) NULL,
    CONSTRAINT [pk_MVPollSubmission] PRIMARY KEY CLUSTERED ([PollSubmissionID] ASC)
);


GO
PRINT N'Creating [dbo].[MVReportedPoll]...';


GO
CREATE TABLE [dbo].[MVReportedPoll] (
    [ReportedPollID]            INT            IDENTITY (1, 1) NOT NULL,
    [PollID]                    INT            NOT NULL,
    [ReportedByUserID]          INT            NOT NULL,
    [CurrentStateAdminUserID]   INT            NULL,
    [DateReported]              DATETIME2 (7)  NOT NULL,
    [DateCurrentStateChanged]   DATETIME2 (7)  NULL,
    [ReportedPollStateOptionID] INT            NOT NULL,
    [ReportComments]            NVARCHAR (500) NULL,
    CONSTRAINT [pk_MVReportedPoll] PRIMARY KEY CLUSTERED ([ReportedPollID] ASC)
);


GO
PRINT N'Creating [dbo].[MVReportedPollStateLog]...';


GO
CREATE TABLE [dbo].[MVReportedPollStateLog] (
    [ReportedPollStateLogID] INT            IDENTITY (1, 1) NOT NULL,
    [ReportedPollID]         INT            NOT NULL,
    [PollID]                 INT            NOT NULL,
    [StateAdminUserID]       INT            NOT NULL,
    [DateStateChanged]       DATETIME2 (7)  NOT NULL,
    [StateChangeComments]    NVARCHAR (500) NULL,
    CONSTRAINT [pk_MVReportedPollStateLog] PRIMARY KEY CLUSTERED ([ReportedPollStateLogID] ASC)
);


GO
PRINT N'Creating [dbo].[MVReportedPollStateOption]...';


GO
CREATE TABLE [dbo].[MVReportedPollStateOption] (
    [ReportedPollStateOptionID] INT            NOT NULL,
    [ReportedPollStateName]     NVARCHAR (50)  NOT NULL,
    [ReportedPollStateComments] NVARCHAR (500) NULL,
    CONSTRAINT [pk_MVReportedPollStateOption] PRIMARY KEY CLUSTERED ([ReportedPollStateOptionID] ASC)
);


GO
PRINT N'Creating [dbo].[MVUser]...';


GO
CREATE TABLE [dbo].[MVUser] (
    [UserID]           INT             IDENTITY (1, 1) NOT NULL,
    [UserName]         NVARCHAR (200)  NOT NULL,
    [ProfileID]        NVARCHAR (200)  NULL,
    [ProfileAuthToken] NVARCHAR (2100) NULL,
    [EmailAddress]     NVARCHAR (200)  NOT NULL,
    [FirstName]        NVARCHAR (100)  NULL,
    [LastName]         NVARCHAR (100)  NULL,
    [Gender]           NCHAR (1)       NULL,
    [PostalCode]       NVARCHAR (20)   NULL,
    [BirthDate]        DATE            NULL,
    [UserRoleID]       INT             NULL,
    [AuditCreateDate]  DATETIME2 (7)   NULL,
    [AuditModifyDate]  DATETIME2 (7)   NULL,
    CONSTRAINT [pk_MVUser] PRIMARY KEY NONCLUSTERED ([UserID] ASC)
);


GO
PRINT N'Creating [dbo].[MVUser].[cuidx_MVUser_UserName]...';


GO
CREATE UNIQUE CLUSTERED INDEX [cuidx_MVUser_UserName]
    ON [dbo].[MVUser]([UserName] ASC);


GO
PRINT N'Creating [dbo].[MVUserRole]...';


GO
CREATE TABLE [dbo].[MVUserRole] (
    [UserRoleID]   INT            IDENTITY (1, 1) NOT NULL,
    [UserRoleName] NVARCHAR (100) NOT NULL,
    CONSTRAINT [pk_MVRole] PRIMARY KEY CLUSTERED ([UserRoleID] ASC)
);


GO
PRINT N'Creating [dbo].[df_DateReported]...';


GO
ALTER TABLE [dbo].[MVReportedPoll]
    ADD CONSTRAINT [df_DateReported] DEFAULT (getutcdate()) FOR [DateReported];


GO
PRINT N'Creating [dbo].[df_MVUser_AuditCreateDate]...';


GO
ALTER TABLE [dbo].[MVUser]
    ADD CONSTRAINT [df_MVUser_AuditCreateDate] DEFAULT (getutcdate()) FOR [AuditCreateDate];


GO
PRINT N'Creating [dbo].[fk_MVPoll_MVUser]...';


GO
ALTER TABLE [dbo].[MVPoll] WITH NOCHECK
    ADD CONSTRAINT [fk_MVPoll_MVUser] FOREIGN KEY ([UserID]) REFERENCES [dbo].[MVUser] ([UserID]);


GO
PRINT N'Creating [dbo].[FK_MVPoll_MVCategory]...';


GO
ALTER TABLE [dbo].[MVPoll] WITH NOCHECK
    ADD CONSTRAINT [FK_MVPoll_MVCategory] FOREIGN KEY ([PollCategoryID]) REFERENCES [dbo].[MVCategory] ([CategoryID]);


GO
PRINT N'Creating [dbo].[fk_MVUser_MVPollComment]...';


GO
ALTER TABLE [dbo].[MVPollComment] WITH NOCHECK
    ADD CONSTRAINT [fk_MVUser_MVPollComment] FOREIGN KEY ([UserID]) REFERENCES [dbo].[MVUser] ([UserID]);


GO
PRINT N'Creating [dbo].[fk_MVPoll_MVPollComment]...';


GO
ALTER TABLE [dbo].[MVPollComment] WITH NOCHECK
    ADD CONSTRAINT [fk_MVPoll_MVPollComment] FOREIGN KEY ([PollID]) REFERENCES [dbo].[MVPoll] ([PollID]);


GO
PRINT N'Creating [dbo].[fk_MVPoll_MVPollOption]...';


GO
ALTER TABLE [dbo].[MVPollOption] WITH NOCHECK
    ADD CONSTRAINT [fk_MVPoll_MVPollOption] FOREIGN KEY ([PollID]) REFERENCES [dbo].[MVPoll] ([PollID]);


GO
PRINT N'Creating [dbo].[fk_MVPoll_MVPollResponse]...';


GO
ALTER TABLE [dbo].[MVPollResponse] WITH NOCHECK
    ADD CONSTRAINT [fk_MVPoll_MVPollResponse] FOREIGN KEY ([PollID]) REFERENCES [dbo].[MVPoll] ([PollID]);


GO
PRINT N'Creating [dbo].[fk_MVPollSubmission_MVPollResponse]...';


GO
ALTER TABLE [dbo].[MVPollResponse] WITH NOCHECK
    ADD CONSTRAINT [fk_MVPollSubmission_MVPollResponse] FOREIGN KEY ([PollSubmissionID]) REFERENCES [dbo].[MVPollSubmission] ([PollSubmissionID]);


GO
PRINT N'Creating [dbo].[fk_MVUser_MVPollResponse]...';


GO
ALTER TABLE [dbo].[MVPollResponse] WITH NOCHECK
    ADD CONSTRAINT [fk_MVUser_MVPollResponse] FOREIGN KEY ([UserID]) REFERENCES [dbo].[MVUser] ([UserID]);


GO
PRINT N'Creating [dbo].[fk_MVPollOption_MVPollResponse]...';


GO
ALTER TABLE [dbo].[MVPollResponse] WITH NOCHECK
    ADD CONSTRAINT [fk_MVPollOption_MVPollResponse] FOREIGN KEY ([PollOptionID]) REFERENCES [dbo].[MVPollOption] ([PollOptionID]);


GO
PRINT N'Creating [dbo].[fk_MVPoll_MVPollSubmission]...';


GO
ALTER TABLE [dbo].[MVPollSubmission] WITH NOCHECK
    ADD CONSTRAINT [fk_MVPoll_MVPollSubmission] FOREIGN KEY ([PollID]) REFERENCES [dbo].[MVPoll] ([PollID]);


GO
PRINT N'Creating [dbo].[fk_MVUser_MVPollSubmission]...';


GO
ALTER TABLE [dbo].[MVPollSubmission] WITH NOCHECK
    ADD CONSTRAINT [fk_MVUser_MVPollSubmission] FOREIGN KEY ([UserID]) REFERENCES [dbo].[MVUser] ([UserID]);


GO
PRINT N'Creating [dbo].[fk_MVPoll_MVReportedPoll]...';


GO
ALTER TABLE [dbo].[MVReportedPoll] WITH NOCHECK
    ADD CONSTRAINT [fk_MVPoll_MVReportedPoll] FOREIGN KEY ([PollID]) REFERENCES [dbo].[MVPoll] ([PollID]);


GO
PRINT N'Creating [dbo].[fk_ReportedByUser_MVReportedPoll]...';


GO
ALTER TABLE [dbo].[MVReportedPoll] WITH NOCHECK
    ADD CONSTRAINT [fk_ReportedByUser_MVReportedPoll] FOREIGN KEY ([ReportedByUserID]) REFERENCES [dbo].[MVUser] ([UserID]);


GO
PRINT N'Creating [dbo].[fk_CurrentStateAdminUser_MVReportedPoll]...';


GO
ALTER TABLE [dbo].[MVReportedPoll] WITH NOCHECK
    ADD CONSTRAINT [fk_CurrentStateAdminUser_MVReportedPoll] FOREIGN KEY ([CurrentStateAdminUserID]) REFERENCES [dbo].[MVUser] ([UserID]);


GO
PRINT N'Creating [dbo].[fk_MVReportedPollStateOption_MVReportedPoll]...';


GO
ALTER TABLE [dbo].[MVReportedPoll] WITH NOCHECK
    ADD CONSTRAINT [fk_MVReportedPollStateOption_MVReportedPoll] FOREIGN KEY ([ReportedPollStateOptionID]) REFERENCES [dbo].[MVReportedPollStateOption] ([ReportedPollStateOptionID]);


GO
PRINT N'Creating [dbo].[fk_MVReportedPoll_MVReportedPollStateLog]...';


GO
ALTER TABLE [dbo].[MVReportedPollStateLog] WITH NOCHECK
    ADD CONSTRAINT [fk_MVReportedPoll_MVReportedPollStateLog] FOREIGN KEY ([ReportedPollID]) REFERENCES [dbo].[MVReportedPoll] ([ReportedPollID]);


GO
PRINT N'Creating [dbo].[fk_MVPoll_MVReportedPollStateLog]...';


GO
ALTER TABLE [dbo].[MVReportedPollStateLog] WITH NOCHECK
    ADD CONSTRAINT [fk_MVPoll_MVReportedPollStateLog] FOREIGN KEY ([PollID]) REFERENCES [dbo].[MVPoll] ([PollID]);


GO
PRINT N'Creating [dbo].[fk_StateAdminUser_MVReportedPollStateLog]...';


GO
ALTER TABLE [dbo].[MVReportedPollStateLog] WITH NOCHECK
    ADD CONSTRAINT [fk_StateAdminUser_MVReportedPollStateLog] FOREIGN KEY ([StateAdminUserID]) REFERENCES [dbo].[MVUser] ([UserID]);


GO
PRINT N'Creating [dbo].[fk_MVUser_MVUserRole]...';


GO
ALTER TABLE [dbo].[MVUser] WITH NOCHECK
    ADD CONSTRAINT [fk_MVUser_MVUserRole] FOREIGN KEY ([UserRoleID]) REFERENCES [dbo].[MVUserRole] ([UserRoleID]);


GO
PRINT N'Creating [Reports].[Responding User]...';


GO
create view [Reports].[Responding User] 
with schemabinding 
as 
SELECT [UserID] as [User Id]
      ,case [Gender] when '' then 'Unspecified' when 'M' then 'Male' when 'F' then 'Female' else 'Unspecified' end as Gender
      ,[PostalCode] as [Zip Code]
      ,[BirthDate] as [Date of Birth]
	  ,datediff(year,birthdate,getdate()) as Age
  FROM [dbo].[MVUser]
GO
PRINT N'Creating [Reports].[Polls]...';


GO
create view [Reports].[Polls] 
with schemabinding 
as 
SELECT [PollID] as [Poll Id]
      ,[UserID] as [User Id]
      ,[PollCategoryID] as [Category Id]
      ,[PollQuestion] as [Question]
      ,[PollDescription] as [Description]
      ,[PollImageLink] as [Image Link]
      ,[PollMaxAnswers] as [Max Answers]
      ,[PollMinAnswers] as [Min Answers]
      ,[PollStartDate] as [Start Date]
	  ,convert(int,convert(varchar,PollStartDate,112)) as [Start Date Id]
      ,[PollEndDate] as [End Date]
	  ,convert(int,convert(varchar,PollEndDate,112)) as [End Date Id]
      --,[PollAdminRemovedFlag]
      --,[PollDateRemoved]
      --,[PollDeletedFlag]
      --,[PollDeletedDate]
      ,[AuditDateCreated] as [Date Created]
	  ,convert(int,convert(varchar,AuditDateCreated,112)) as [Date Created Id]
      ,[AuditDateModified] as [Date Modified]
	  ,convert(int,convert(varchar,AuditDateModified,112)) as [Date Modified Id]
  FROM [dbo].[MVPoll] 
  where [PollDeletedFlag] = 0
GO
PRINT N'Creating [Reports].[Poll Submissions]...';


GO


create view [Reports].[Poll Submissions] 
with schemabinding 
as
SELECT [PollSubmissionID] as [Poll Submission Id] 
      ,[PollID] as [Poll Id]
      ,[UserID] as [User Id]
      ,[PollSubmissionDate] as [Date]
	  ,convert(int,convert(varchar,PollSubmissionDate,112)) as [Date Id]
      ,[PollSubmissionComment] as [Comment]
  FROM [dbo].[MVPollSubmission]
GO
PRINT N'Creating [Reports].[Poll Responses]...';


GO

create view [Reports].[Poll Responses] 
with schemabinding 
as
SELECT [PollResponseID] as [Poll Response Id]
      ,[PollID] as [Poll Id]
      ,[PollSubmissionID] as [Poll Submission Id]
      ,[UserID] as [User Id]
      ,[PollOptionID] as [Poll Option Id]
      ,[OptionSelected] as [Option Selected]
      ,[ResponseDate] as [Response Date]
	  ,convert(int,convert(varchar,ResponseDate,112)) as [Date Id]
  FROM [dbo].[MVPollResponse]
GO
PRINT N'Creating [Reports].[Poll Owner]...';


GO
create view [Reports].[Poll Owner] 
with schemabinding 
as 
SELECT [UserID] as [User Id]
      ,[UserName] as [User Name]
      ,[ProfileID] as [Profile Id]
      ,[EmailAddress] as [Email Address]
      ,[FirstName] as [First Name]
      ,[LastName] as [Last Name]
      ,[Gender]
      ,[PostalCode] as [Zip Code]
      ,[BirthDate] as [Date of Birth]
  FROM [dbo].[MVUser]
GO
PRINT N'Creating [Reports].[Poll Options]...';


GO

create view [Reports].[Poll Options] 
with schemabinding 
as
SELECT [PollOptionID] as [Poll Option Id]
      ,[PollID] as [Poll Id]
      ,[OptionPosition] as [Option Position]
      ,[OptionText] as [Option Text]
  FROM [dbo].[MVPollOption]
GO
PRINT N'Creating [Reports].[Geography]...';


GO
create view [Reports].[Geography] 
with schemabinding 
as
SELECT [GeographyKey] as [Geography Id]
      ,[Zip]  as [Zip Code]
      ,[Primary_City] as [City]
      ,[State] as [State]
      ,[County] as [County]
      ,[TimeZone] as [Time Zone]
      ,[Area_Codes] as [Area Codes]
      ,cast([Latitude] as double precision) as [Latitude]
      ,cast([Longitude] as double precision) as [Longitude]
      ,cast([Estimated_Population] as int) as [Population]
  FROM [dbo].[MVGeography]
GO
PRINT N'Creating [Reports].[Dates]...';


GO

create view [Reports].[Dates]
with schemabinding as 
SELECT [DateKey] as [Date Id]
      ,[DateID] as [Date]
      ,[DayNme] as [Day Name]
      ,[DayShort] as [Short Day Name]
      ,[CalendarYear] as [Year]
      ,[CalendarQuarter] as [Quarter]
      ,[CalendarQuarterName] as [Quarter Name]
      ,[CalendarQuarterShort] as [Short Quarter Name]
      ,[CalendarMonth] as [Month]
      ,[CalendarMonthName] as [Month Name]
      ,[CalendarMonthShort] as [Short Month Name]
      ,[CalendarWeek] as [Week Number]
      ,[CalendarWeekName] as [Week Name]
      ,[CalendarWeekShort] as [Short Week Name]
  FROM [dbo].[MVDates]
GO
PRINT N'Creating [Reports].[Categories]...';


GO


create view [Reports].[Categories] 
with schemabinding 
as 
SELECT [CategoryID] as [Category Id]
      ,[CategoryName] as [Category Name]
  FROM [dbo].[MVCategory]
GO
PRINT N'Creating [dbo].[dimDate]...';


GO
create view [dbo].[dimDate]
	as select 
		  DateKey
		  ,DateID
		  ,CalendarYear
		  ,CalendarQuarter
		  ,CalendarQuarterShort
		  ,CalendarMonth
		  ,CalendarMonthShort
	   from dbo.MVDates
GO
PRINT N'Creating [dbo].[dimPoll]...';


GO
create view [dbo].[dimPoll]
	as select
		mvp.PollID
		,mvp.PollQuestion
		,mvp.PollCategoryID
		,mvc.CategoryName as PollCategoryName
		from dbo.MVPoll mvp
			inner join dbo.MVCategory mvc on mvp.PollCategoryID = mvc.CategoryID
GO
PRINT N'Creating [dbo].[dimUser]...';


GO
create view [dbo].[dimUser]
	as select 
		mvu.UserID
		,mvu.UserName
		,mvu.Gender
		,isnull(mvg.State, 'XX') as State
		,isnull(mvg.Primary_City, 'Unknown') as City
		from dbo.MVUser mvu
			left join dbo.MVGeography mvg on mvu.PostalCode = mvg.Zip
GO
PRINT N'Creating [dbo].[factMVPollSubmission]...';


GO

create view [dbo].[factMVPollSubmission]
as
select 
	PollID
	,UserID
	,cast(convert(varchar, PollSubmissionDate, 112) as int) as DateKey
	,1 as SubmissionCount
from dbo.MVPollSubmission
GO
PRINT N'Creating [dbo].[UserPollsByCategory]...';


GO
create view [dbo].[UserPollsByCategory]
as
select  UserName
  , [Fun]
  , [Sports]
  , [Technology]
  , [Off-Topic]
  , [Entertainment]
from
 (select p.PollID, c.CategoryName, u.UserName
     from dbo.MVPoll p
     inner join dbo.MVCategory c on p.PollCategoryID = c.CategoryID
     inner join dbo.MVUser u on p.UserID = u.UserID
  ) as sourcetable
pivot
 (count(PollID)
   for CategoryName in ([Fun]
  , [Sports]
  , [Technology]
  , [Off-Topic]
  , [Entertainment])
) as pivottable
;
GO
PRINT N'Creating [Reports].[Submission Date]...';


GO

create view [Reports].[Submission Date] 
with schemabinding 
as 
select  
[Date Id]
,[Date]
,[Day Name]
,[Short Day Name]
,[Year]
,[Quarter]
,[Quarter Name]
,[Short Quarter Name]
,[Month]
,[Month Name]
,[Short Month Name]
,[Week Number]
,[Week Name]
,[Short Week Name]
from Reports.Dates
GO
PRINT N'Creating [Reports].[Response Date]...';


GO

create view [Reports].[Response Date] with schemabinding 
as select 
[Date Id]
,[Date]
,[Day Name]
,[Short Day Name]
,[Year]
,[Quarter]
,[Quarter Name]
,[Short Quarter Name]
,[Month]
,[Month Name]
,[Short Month Name]
,[Week Number]
,[Week Name]
,[Short Week Name]
from Reports.Dates
GO
PRINT N'Creating [dbo].[deletePoll]...';


GO
CREATE PROCEDURE [dbo].[deletePoll]
	@PollID int
AS
	
delete from dbo.MVReportedPollStateLog where PollID = @PollID;

delete from dbo.MVReportedPoll where PollID = @PollID;

delete from dbo.MVPollResponse where PollID = @PollID;

delete from dbo.MVPollSubmission where PollID = @PollID;

delete from dbo.MVPollOption where PollID = @PollID;

delete from dbo.MVPoll where PollID = @PollID;


RETURN 0
GO
-- Update or load new categories

merge dbo.MVCategory as target
using (
		select 1, 'Fun'
		union
		select 2, 'Technology'
		union
		select 3, 'Entertainment'
		union
		select 4, 'News'
		union
		select 5, 'Sports'
		union
		select 6, 'Off-Topic'
	) as source (CategoryID, CategoryName)
	on target.CategoryID = source.CategoryID
when matched then
	update set target.CategoryName = source.CategoryName
when not matched then 
	insert (CategoryID, CategoryName) values (source.CategoryID, source.CategoryName)
;
GO

GO
