#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyVote.UI.Resource", IsApplication=true)]

namespace MyVote.UI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Csla.Resource.String.ApplicationName = global::MyVote.UI.Resource.String.ApplicationName;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::MyVote.UI.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::MyVote.UI.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::MyVote.UI.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::MyVote.UI.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::MyVote.UI.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::MyVote.UI.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::MyVote.UI.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::MyVote.UI.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::MyVote.UI.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::MyVote.UI.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::MyVote.UI.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::MyVote.UI.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::MyVote.UI.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::MyVote.UI.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::MyVote.UI.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::MyVote.UI.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::MyVote.UI.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::MyVote.UI.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::MyVote.UI.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::MyVote.UI.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::MyVote.UI.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MyVote.BusinessObjects.Resource.String.ApplicationName = global::MyVote.UI.Resource.String.ApplicationName;
			global::MyVote.BusinessObjects.Resource.String.Hello = global::MyVote.UI.Resource.String.Hello;
			global::MyVote.Core.Resource.String.ApplicationName = global::MyVote.UI.Resource.String.ApplicationName;
			global::MyVote.Core.Resource.String.Hello = global::MyVote.UI.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int MyVoteOrange = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_myvote = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_myvote = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_myvote = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_myvote = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_myvote = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_myvote = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_cab_done_default_myvote = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_focused_myvote = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_myvote = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_pressed_myvote = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cab_background_bottom_myvote = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cab_background_top_myvote = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int GooglePlay = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_error_white_24dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int IconFacebook = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int IconGoogle = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int IconMicrosoft = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int IconTwitter = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int list_focused_myvote = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int list_pressed_myvote = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int logo = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int menu_dropdown_panel_myvote = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int MoreMenu = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int NoImage = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int progress_bg_myvote = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int progress_horizontal_myvote = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int progress_primary_myvote = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int progress_secondary_myvote = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int selectable_background_myvote = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int spinner_ab_default_myvote = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int spinner_ab_disabled_myvote = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int spinner_ab_focused_myvote = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int spinner_ab_pressed_myvote = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int spinner_background_ab_myvote = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tab_indicator_ab_myvote = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int tab_selected_focused_myvote = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int tab_selected_myvote = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int tab_selected_pressed_myvote = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int tab_unselected_focused_myvote = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int tab_unselected_myvote = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int tab_unselected_pressed_myvote = 2130837545;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int SplashScreen = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060003
			public const int ActionBar_Solid_Myvote = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int ActionBar_Transparent_Myvote = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int ActionBarTabStyle_Myvote = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int ActionButton_CloseMode_Myvote = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int DropDownListView_Myvote = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int DropDownNav_Myvote = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int PopupMenu_Myvote = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int ProgressBar_Myvote = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int Theme_MyVoteAll = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_MyVoteListView = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Theme_Myvote = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int Theme_Myvote_Widget = 2131099659;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
