//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace MyVote.Repository
{
    [GeneratedCode("DbContext 1.0.2.0", "EF 4.3.1")]
    [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
    public partial class MVDate
    {
        public int DateKey { get; set; }
        public System.DateTime DateID { get; set; }
        public string DayNme { get; set; }
        public string DayShort { get; set; }
        public byte DayNOD { get; set; }
        public short CalendarYear { get; set; }
        public short CalendarYearNOD { get; set; }
        public int CalendarQuarter { get; set; }
        public string CalendarQuarterName { get; set; }
        public string CalendarQuarterShort { get; set; }
        public byte CalendarQuarterNOD { get; set; }
        public int CalendarMonth { get; set; }
        public string CalendarMonthName { get; set; }
        public string CalendarMonthShort { get; set; }
        public byte CalendarMonthNOD { get; set; }
        public int CalendarWeek { get; set; }
        public string CalendarWeekName { get; set; }
        public string CalendarWeekShort { get; set; }
        public byte CalendarWeekNOD { get; set; }
    }
    
}
