//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace MyVote.Repository
{
    [GeneratedCode("DbContext 1.0.2.0", "EF 4.3.1")]
    [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
    public partial class MVGeography
    {
        public int GeographyKey { get; set; }
        public string zip { get; set; }
        public string primary_city { get; set; }
        public string state { get; set; }
        public string county { get; set; }
        public string timezone { get; set; }
        public string area_codes { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string estimated_population { get; set; }
    }
    
}
