//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace MyVote.Repository
{
    [GeneratedCode("DbContext 1.0.2.0", "EF 4.3.1")]
    [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
    public partial class MVPoll
    {
        [GeneratedCode("DbContext 1.0.2.0", "EF 4.3.1")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        public MVPoll()
        {
            this.MVPollComments = new HashSet<MVPollComment>();
            this.MVPollOptions = new HashSet<MVPollOption>();
            this.MVPollResponses = new HashSet<MVPollResponse>();
            this.MVPollSubmissions = new HashSet<MVPollSubmission>();
            this.MVReportedPolls = new HashSet<MVReportedPoll>();
            this.MVReportedPollStateLogs = new HashSet<MVReportedPollStateLog>();
        }
    
        public int PollID { get; set; }
        public int UserID { get; set; }
        public int PollCategoryID { get; set; }
        public string PollQuestion { get; set; }
        public string PollDescription { get; set; }
        public string PollImageLink { get; set; }
        public Nullable<short> PollMaxAnswers { get; set; }
        public Nullable<short> PollMinAnswers { get; set; }
        public System.DateTime PollStartDate { get; set; }
        public System.DateTime PollEndDate { get; set; }
        public Nullable<bool> PollAdminRemovedFlag { get; set; }
        public Nullable<System.DateTime> PollDateRemoved { get; set; }
        public Nullable<bool> PollDeletedFlag { get; set; }
        public Nullable<System.DateTime> PollDeletedDate { get; set; }
        public Nullable<System.DateTime> AuditDateCreated { get; set; }
        public Nullable<System.DateTime> AuditDateModified { get; set; }
    
        public virtual MVCategory MVCategory { get; set; }
        public virtual ICollection<MVPollComment> MVPollComments { get; set; }
        public virtual ICollection<MVPollOption> MVPollOptions { get; set; }
        public virtual ICollection<MVPollResponse> MVPollResponses { get; set; }
        public virtual ICollection<MVPollSubmission> MVPollSubmissions { get; set; }
        public virtual ICollection<MVReportedPoll> MVReportedPolls { get; set; }
        public virtual ICollection<MVReportedPollStateLog> MVReportedPollStateLogs { get; set; }
        public virtual MVUser MVUser { get; set; }
    }
    
}
