//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace MyVote.Repository
{
    [GeneratedCode("DbContext 1.0.2.0", "EF 4.3.1")]
    [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
    public partial class MVReportedPoll
    {
        [GeneratedCode("DbContext 1.0.2.0", "EF 4.3.1")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        public MVReportedPoll()
        {
            this.MVReportedPollStateLogs = new HashSet<MVReportedPollStateLog>();
        }
    
        public int ReportedPollID { get; set; }
        public int PollID { get; set; }
        public int ReportedByUserID { get; set; }
        public Nullable<int> CurrentStateAdminUserID { get; set; }
        public System.DateTime DateReported { get; set; }
        public Nullable<System.DateTime> DateCurrentStateChanged { get; set; }
        public int ReportedPollStateOptionID { get; set; }
        public string ReportComments { get; set; }
    
        public virtual MVPoll MVPoll { get; set; }
        public virtual MVUser MVUser { get; set; }
        public virtual ICollection<MVReportedPollStateLog> MVReportedPollStateLogs { get; set; }
        public virtual MVReportedPollStateOption MVReportedPollStateOption { get; set; }
        public virtual MVUser MVUser1 { get; set; }
    }
    
}
