//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVote.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVGeography
    {
        public int GeographyKey { get; set; }
        public string Zip { get; set; }
        public string Primary_City { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string TimeZone { get; set; }
        public string Area_Codes { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Estimated_Population { get; set; }
    }
}
