//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVote.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPollComment
    {
        public int PollCommentID { get; set; }
        public int UserID { get; set; }
        public string CommentText { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<int> ParentCommentID { get; set; }
        public int PollID { get; set; }
        public Nullable<bool> PollCommentDeletedFlag { get; set; }
        public Nullable<System.DateTime> PollCommentDeletedDate { get; set; }
    
        public virtual MVPoll MVPoll { get; set; }
        public virtual MVUser MVUser { get; set; }
    }
}
