//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVote.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPollResponse
    {
        public int PollResponseID { get; set; }
        public int PollID { get; set; }
        public int PollSubmissionID { get; set; }
        public int UserID { get; set; }
        public int PollOptionID { get; set; }
        public bool OptionSelected { get; set; }
        public System.DateTime ResponseDate { get; set; }
    
        public virtual MVPoll MVPoll { get; set; }
        public virtual MVPollOption MVPollOption { get; set; }
        public virtual MVPollSubmission MVPollSubmission { get; set; }
        public virtual MVUser MVUser { get; set; }
    }
}
