//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVote.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPollSubmission
    {
        public MVPollSubmission()
        {
            this.MVPollResponses = new HashSet<MVPollResponse>();
        }
    
        public int PollSubmissionID { get; set; }
        public int PollID { get; set; }
        public int UserID { get; set; }
        public System.DateTime PollSubmissionDate { get; set; }
        public string PollSubmissionComment { get; set; }
    
        public virtual MVPoll MVPoll { get; set; }
        public virtual ICollection<MVPollResponse> MVPollResponses { get; set; }
        public virtual MVUser MVUser { get; set; }
    }
}
