//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVote.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPollOption
    {
        public MVPollOption()
        {
            this.MVPollResponses = new HashSet<MVPollResponse>();
        }
    
        public int PollOptionID { get; set; }
        public int PollID { get; set; }
        public short OptionPosition { get; set; }
        public string OptionText { get; set; }
    
        public virtual MVPoll MVPoll { get; set; }
        public virtual ICollection<MVPollResponse> MVPollResponses { get; set; }
    }
}
