//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVote.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVReportedPoll
    {
        public MVReportedPoll()
        {
            this.MVReportedPollStateLogs = new HashSet<MVReportedPollStateLog>();
        }
    
        public int ReportedPollID { get; set; }
        public int PollID { get; set; }
        public int ReportedByUserID { get; set; }
        public Nullable<int> CurrentStateAdminUserID { get; set; }
        public System.DateTime DateReported { get; set; }
        public Nullable<System.DateTime> DateCurrentStateChanged { get; set; }
        public int ReportedPollStateOptionID { get; set; }
        public string ReportComments { get; set; }
    
        public virtual MVPoll MVPoll { get; set; }
        public virtual MVUser MVUser { get; set; }
        public virtual ICollection<MVReportedPollStateLog> MVReportedPollStateLogs { get; set; }
        public virtual MVReportedPollStateOption MVReportedPollStateOption { get; set; }
        public virtual MVUser MVUser1 { get; set; }
    }
}
