//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVote.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVReportedPollStateOption
    {
        public MVReportedPollStateOption()
        {
            this.MVReportedPolls = new HashSet<MVReportedPoll>();
        }
    
        public int ReportedPollStateOptionID { get; set; }
        public string ReportedPollStateName { get; set; }
        public string ReportedPollStateComments { get; set; }
    
        public virtual ICollection<MVReportedPoll> MVReportedPolls { get; set; }
    }
}
