//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVote.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVReportedPollStateLog
    {
        public int ReportedPollStateLogID { get; set; }
        public int ReportedPollID { get; set; }
        public int PollID { get; set; }
        public int StateAdminUserID { get; set; }
        public System.DateTime DateStateChanged { get; set; }
        public string StateChangeComments { get; set; }
    
        public virtual MVPoll MVPoll { get; set; }
        public virtual MVReportedPoll MVReportedPoll { get; set; }
        public virtual MVUser MVUser { get; set; }
    }
}
