//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVote.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVUserRole
    {
        public MVUserRole()
        {
            this.MVUsers = new HashSet<MVUser>();
        }
    
        public int UserRoleID { get; set; }
        public string UserRoleName { get; set; }
    
        public virtual ICollection<MVUser> MVUsers { get; set; }
    }
}
